### ISSUE TITLE
Great start

### ISSUE THREAD

**Issue by gedw99** [z0mbie42/goes#2]
For the few days I was playing around with mixing together graphql and an event store.
Nice I found this.

I have one request :)
Use a pure golang db with bleve.
Bleve gives your search and indexing.
Badgerdb gives you a high performance db.
The only bit missing is a query language that is interpreted.

Ultimately you want to commands and events to be above the golang level. I know this sounds weird but it a good test of a system like this because you really want many languages to be able to use the eventing system.
This means in practice that you expose the events over a pub sub like NATs golang pub sub does.

I saw that the ipfs team have a query layer working with badgerdb.

Anyway I just wanted to raise this.
Will dick deeper into this code.

**Comment by z0mbie42** [comment]
Hi, thank you very much for the feedback!

Concerning the event store, the goal is to have an adaptater abstraction layer to be event store indipendant (the requirement is to support transactions).
Concerning bleve, as a Text search engine, I think it fit better for a pure read model populated by the "reactors" which respond to events.

Furthermore using an embedded event store limit horizontal scalability.

Concerning the commands, For the moment I want to keep it KISS (https://kickstarter.engineering/event-sourcing-made-simple-4a2625113224), so all the domain logic should be in golang. One way to use this framework in an micro service environment is the following:
```
graphql layer |
              | -> goes command 1 -> event type 1 -> reactor subscribed to event type 1 -> publish to NAT -> forward to other services subscribing to event type 1
              | -> goes command 2 -> event type 2 ->  reactor subscribed to event type 2


```

**Comment by gedw99** [comment]
Yep I get all that. Thanks for the flow diagram.

I am wanting to do something a bit different and your graphql schema allows it.

What if you treat each browser app as a microservice subscribing to the CQRS system ? This is what I think your system offers. Because of gophers is just the same code ( is or WASM ). 

The pub sub and db stays on the server but the events, commands and "reactors" and aggregations stay on the client.

Why ?

Because reflux and all the other ways of doing state management in clients is really just A form of CQRS.
This is what I badly explained in my first post :) sorry about that.

The really cool thing is that because it's a web app then when you change your server code the client code is updated instantly so you remove a whole class of schema evolution problems.

It also doing offline web apps easily too but  don't really want to go all the way down that rabbit hole now as I don't want to confuse the purity of the idea I am sort of "pitching" here.

Also it's important for me to state that it's all golang code so not chore like work :) just a matter of running some of the code on the client.

This is not super easy to get your head around. It's subtle what this offers. But the best way to explain it I have found is to just think of the software tuning in the browser as a webserver but with a GUI.
Now because you have events and viewmodel ( aka aggregations ) in the GUI layer written seriously amazing GUIs with gophers because child's play.
In. Fact vuejs has a " reactive backpressure" layer that can tap into the event / viewmodel easily.

**Comment by z0mbie42** [comment]
Hi,

Sorry for not responding before, I was quite busy.

As mentioned in #3 I'm quiet happy with the current state of goes and do not plan to Add any major feature in the near future.

I think goes should be seen as a simple lightweight framework to create event sourced systems in Go, but not a big giant framework which should enable distributed event sourced systems.

**Comment by gedw99** [comment]
Thanks.
I was the person that helped with some of the fundamental design of it.
Ironically :)
