### ISSUE TITLE
cockroachdb

### ISSUE THREAD

**Issue by gedw99** [z0mbie42/goes#3]
I started to use this with cockroachdb.

https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html

In case your not aware of it CockroachDB is compatible with the Postresql syntax.
See here:
https://www.cockroachlabs.com/docs/stable/install-client-drivers.html

And it works with GORM:
https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb-gorm.html

It also has native cross data center replication, and so al your events persisted will run in all your datacenters.

Its interesting because cockroachDB is a DB that uses some CQRS aspects to do its thing.
you can see it in the events table of the DB and other areas.

anyway, will see if i can get it working.

**Comment by z0mbie42** [comment]
Nice, so you are able to use with cockroachdb without any modification ?

**Comment by gedw99** [comment]
Almost I think. Still messing with it. I will come back soon with it going
:)

**Comment by gedw99** [comment]
saw the new release. Nice. Sorry but i just did not have time to finish the cockroachdb stuff.
Its maybe only 20 minutes work but work is just too intense right now.

Any chance you can sort of do roadmap etc, and maybe basic change log for each release.
Will help me see what needs doing and where i can help.

**Comment by gedw99** [comment]
here is he make file for getting cockroachdb going.

I dont run it in docker because its golang anyway.

All i need to do is finish the connection string. Creation of DB and user.
Can you put this into the root so we can work up it working with cockroach and postres ?

````


# https://github.com/z0mbie42/goes
# cqrs make simple !!



REPO=github.com/z0mbie42/goes
REPO_GOPATH=$(GOPATH)/src/$(REPO)


print:
	@echo

	@echo
	@echo SERVER -
	@echo REPO: $(REPO)
	@echo REPO_GOPATH: $(REPO_GOPATH)
	@echo


dep:
	go get -u $(REPO)

	# OS deps
	brew install cockroach

open:
	code $(REPO_GOPATH)


## DB tier ##
db-open:
	open http://localhost:8080/#/database/system/table/eventlog

db-run:

	cockroach start --insecure --host=localhost

db-setup:
	cockroach sql --insecure -e 'CREATE USER maxroach WITH PASSWORD 'maxroach''
	cockroach user set maxroach --insecure
	cockroach sql --insecure -e 'CREATE DATABASE goes'

db-print:
	# stuff we need to know
	cockroach sql --insecure -e 'SHOW DATABASES'
	cockroach sql --insecure -e 'SHOW TABLES FROM bank'

	#cockroach sql --insecure -e 'SHOW GRANTS ON test.customers FOR bank'

db-clean:
	cockroach sql --insecure -e 'DROP DATABASE goes'

## user tier
run-user:

	export DATABASE="postgres://maxroach:maxroach@localhost/goes?sslmode=disable"
	# postgres://<username>:<password>@<host>:<port>/<database>?<parameters>

	# Use env variable to pick up DB connection string.
	cd $(REPO_GOPATH)/_examples/user && go get -u
	cd $(REPO_GOPATH)/_examples/user && go run main.go







````

**Comment by z0mbie42** [comment]
Hi,
Sorry for the late reply but I was quite busy.

I thought about the boundaries of the framework and I finally think that the database layer should not be it responsability.

here it how I see the things
- HTTP/Rest/graphql
- domain layer
- goes layer
- DB layer (gorm or whatever).

So I will remove the global variable DB and refactor to take this in account.

On other hand, it could be very nice to see a framewok that cover all these layers and bring a full featured http framework to the go land, but it's another project.

**Comment by gedw99** [comment]
But in the way you see things you had the db layer.
I guess you mean the mapping of the structure to the db and all the sal is
not included ?
Sorry if I misunderstood

**Comment by z0mbie42** [comment]
Goes should be database/orm independent.
At the moment, it relies on gorm because it was easier to mix things to have a first prototype working, but goes boundaries should not include any database specific things.
Maybe an adaptater plugin system

**Comment by gedw99** [comment]
Hmm

Still not clear.

1. Are you going remove gorm dependency ? I hope not because multiple db
support is vital.

This original issue was about supporting cockroach and give goes multi data
center ability.
Gorm works with cockroach so please don't change anything
All that is needed is to integrate and test cockroach with the current
architecture.

If you have other approach happy to discuss but please try to be more clear

**Comment by gedw99** [comment]
Sorry about not understanding.
I see your point about the DB.

I have been building everything with boltdb and badger and pretty happy to not have to deal with traditional db.

Anyways if you have any updates on GO ES and roadmap please let me know.
